name: SimplySpawn
main: com.minetexas.simplyspawn.SimplySpawn
version: 0.2
author: ataranlen
description: Random Spawn.
commands:
  rs_setspawn:
    description: Sets the server spawn point to your current position.
    aliases: setspawn
    usage: /<command>
  rs_spawn:
    description: Warps you to the location of the spawn point.
    aliases: spawn
    usage: /<command>
  rs_rspawn:
    description: Warps you to the location of the spawn point.
    aliases: rspawn
    usage: /<command>
  bed:
    description: Warps you to the location of the spawn point.
    aliases: bed
    usage: /<command>
  getbed:
    description: Warps you to the location of the spawn point.
    aliases: spawn
    usage: /<command>
permissions:
  rssetspawn.spawn:
    description: 'Permission to use /spawn'
    default: true
  rssetspawn.rspawn:
    description: 'Permission to use /rspawn'
    default: true
  rssetspawn.setspawn:
    description: 'Permission to use /setspawn'
    default: op
  rssetspawn.bed:
    description: 'Permission to use /bed'
    default: op
  rssetspawn.getbed:
    description: 'Permission to use /getbed'
    default: op
  rssetspawn.reload:
    description: 'Permission to use /ssreload'
    default: op